name: "ZAP Baseline Scan"

on: workflow_dispatch

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/oseki-guy/zaproxy:report-sarif'
          target: 'https://preview.owasp-juice.shop'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-d -a -j --auto -autogenconf /home/zap/zap.yaml'
      - uses: actions/upload-artifact@v3
        with:
          path: /home/zap/zap.yaml
